openapi: 3.0.0
info:
  title: API MediTurno
  version: 1.0.0
  description: Endpoints MediTurno

servers:
  - url: http://localhost:3000
    description: Servidor local de desarrollo

tags:
  - name: Autenticación
    description: Endpoints relacionados con la autenticación de profesionales.
  - name: Consultorios
    description: Endpoints relacionados con la gestión de consultorios.
  - name: Turnos
    description: Endpoints relacionados con turnos médicos.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/sign-in:
    post:
      tags:
        - Autenticación
      summary: Iniciar sesión
      description: Permite a un profesional de la salud iniciar sesión en el sistema.
      requestBody:
        description: Credenciales necesarias para iniciar sesión.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                matricula:
                  type: string
                  pattern: '^[a-zA-Z0-9]{8}$'
                  example: MN12345A
                  description: Matrícula profesional alfanumérica de 8 caracteres
                pin:
                  type: string
                  pattern: '^[0-9]{6}$'
                  example: '123456'
                  description: PIN numérico de 6 dígitos
              required:
                - matricula
                - pin
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: '1234567890'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                    example: ['La matrícula debe tener 8 caracteres']
        '406':
          description: Credenciales incorrectas
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                    example: ['La matrícula o el PIN son incorrectos']

  /consultorios:
    get:
      tags:
        - Consultorios
      summary: Obtener lista de consultorios
      description: Retorna una lista de consultorios disponibles para el profesional.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  consultorios:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: '1'
                        nombre:
                          type: string
                          example: 'Consultorio A'
                        sala:
                          type: string
                          example: '101'
                        especialidad:
                          type: string
                          example: 'Cardiología'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Unauthorized'

  /turnos/{id}:
    get:
      tags:
        - Turnos
      summary: Consultar turnos de un consultorio
      description: Obtiene la lista de turnos programados para un consultorio específico.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          description: ID del consultorio
          required: true
          schema:
            type: string
            example: '1'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  turnos:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: '1'
                        hora:
                          type: string
                          example: '09:00'
                        paciente:
                          type: string
                          example: 'María González'
                        dni:
                          type: string
                          example: '35678912'
                        obraSocial:
                          type: string
                          example: 'OSDE'
                        tipoConsulta:
                          type: string
                          enum: [PRIMERA_VEZ, CONTROL, URGENCIA]
                          example: 'PRIMERA_VEZ'
                        estado:
                          type: string
                          enum: [CONFIRMADO, AUSENTE, EN_ATENCION, FINALIZADO]
                          example: 'CONFIRMADO'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Unauthorized'
        '404':
          description: Consultorio no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'El consultorio solicitado no se encuentra registrado'
